# Generated by Django 3.1.4 on 2022-08-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_delete_review'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
